info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/createUser:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 确认密码
        in: query
        name: repassword
        type: string
      responses: {}
      summary: 新增用户
      tags:
      - 用户模块
  /user/deleteUser:
    get:
      consumes:
      - application/json
      description: 通过用户ID删除用户，需要提供密码和重复密码以进行确认
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 重复密码
        in: query
        name: repassword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 删除用户
      tags:
      - 用户模块
  /user/findUserByNameAndPwd:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 所有用户
      tags:
      - 用户模块
  /user/getUserList:
    get:
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 所有用户
      tags:
      - 用户模块
  /user/updateUser:
    post:
      description: 通过用户ID更新用户的姓名和密码
      parameters:
      - description: id
        in: formData
        name: id
        type: integer
      - description: name
        in: formData
        name: name
        type: string
      - description: password
        in: formData
        name: password
        type: string
      - description: phone
        in: formData
        name: phone
        type: string
      - description: email
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: 'code": 200, "message": "用户信息更新成功" }'
          schema:
            type: string
      summary: 更新用户信息
      tags:
      - 用户模块
swagger: "2.0"
